name: Flake8 Check

on: [push, pull_request]

jobs:
  lint:
    name: Linting with Flake8 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.8.4
      - name: Running Flake8 checks
        run: ./flake8-check
